- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: JAVA-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: mysql-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: systectl service-yaml
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd


